### ISSUE TITLE
Auto: Intake Ball

### ISSUE THREAD

**Issue by dennis99e** [frc5687/2019-robot#65]
1. Elevator to hatch to 2nd
2. Arm to Intake setpoint
3. Run roller till BallIntake = true (use parallel command for this)
4. Arm to secure setpoint
5. Run vacuum
6. Elevator to Secure Cargo setpoint (Might need to create)
7. Elevator to 2nd hatch(test if the ball is actually holding)

**Comment by BenBernardCIS** [comment]
For step 7, I'd rather have a "SecureCargo" command on the Gripper subsystem that runs the vaccuum and "finishes" when the motor amps spike, indicating the ball is scure.  It would leave the motor running.
