### ISSUE TITLE
Auto: Intake relative to Hatch or Cargo mode

### ISSUE THREAD

**Issue by dennis99e** [frc5687/2019-robot#68]
If in Cargo mode run cargo intake.
if in Hatch mode run Hatch intake

**Comment by BenBernardCIS** [comment]
Use the new Configuration enum to track the robot configuration.
This would _seem_ like it should be a CommandGroup, but what you really want is an AutoIntake Command which runs either your AutoIntakeCargo or AutoIntakeHatch command, based on the Robot configuration.
See the "How to schedule a command from within a running command" section on https://wpilib.screenstepslive.com/s/currentCS/m/java/l/599745-scheduling-commands for how to do this.
